lm-eval   --model hf   --model_args pretrained=/home/zhuhuixing/Projects/code/modelzoo/Mistral-7B-Instruct-v0.2,dtype=auto,max_length=4096,parallelize=true   --tasks humaneval  --num_fewshot 0   --batch_size auto   --device cuda   --output_path ./eval_results/Mistral-7B-Instruct.jsonl   --log_samples   --seed 42 --confirm_run_unsafe_code
lm-eval   --model hf   --model_args pretrained=/home/zhuhuixing/Projects/code/modelzoo/Mistral-7B-Instruct-v0.2,dtype=auto,max_length=4096,parallelize=true   --tasks humaneval  --num_fewshot 0   --batch_size auto   --device cuda   --output_path ./eval_results/Mistral-7B-Instruct.jsonl   --log_samples   --seed 42 --apply_chat_template true --confirm_run_unsafe_code
lm-eval   --model hf   --model_args pretrained=/home/zhuhuixing/Projects/code/modelzoo/Mistral-7B-Instruct-v0.2,dtype=auto,max_length=4096,parallelize=true   --tasks mbpp  --num_fewshot 3   --batch_size auto   --device cuda   --output_path ./eval_results/Mistral-7B-Instruct.jsonl   --log_samples   --seed 42 --confirm_run_unsafe_code
lm-eval   --model hf   --model_args pretrained=/home/zhuhuixing/Projects/code/modelzoo/Mistral-7B-Instruct-v0.2,dtype=auto,max_length=4096,parallelize=true   --tasks mbpp  --num_fewshot 3   --batch_size auto   --device cuda   --output_path ./eval_results/Mistral-7B-Instruct.jsonl   --log_samples   --seed 42 --apply_chat_template true --confirm_run_unsafe_code

lm-eval   --model hf   --model_args pretrained=/home/zhuhuixing/Projects/code/modelzoo/Qwen2.5-Math-7B-Instruct,dtype=auto,max_length=4096   --tasks gsm8k_cot  --num_fewshot 8   --batch_size auto   --device cuda   --output_path ./eval_results/Qwen2.5_Math_7B_gsm8k_results.jsonl   --log_samples   --seed 42 --apply_chat_template true
lm-eval   --model hf   --model_args pretrained=/home/zhuhuixing/Projects/code/modelzoo/Qwen2.5-Math-7B-Instruct,dtype=auto,max_length=4096   --tasks gsm8k_cot  --num_fewshot 8   --batch_size auto   --device cuda   --output_path ./eval_results/Qwen2.5_Math_7B_gsm8k_results.jsonl   --log_samples   --seed 42 
lm-eval   --model hf   --model_args pretrained=/home/zhuhuixing/Projects/code/modelzoo/Qwen2.5-Math-7B-Instruct,dtype=auto,max_length=4096   --tasks gsm8k  --num_fewshot 8   --batch_size auto   --device cuda   --output_path ./eval_results/Qwen2.5_Math_7B_gsm8k_results.jsonl   --log_samples   --seed 42 

lm-eval   --model hf   --model_args pretrained=/home/zhuhuixing/Projects/code/modelzoo/Qwen2.5-Math-7B-Instruct,dtype=auto,max_length=4096   --tasks gsm8k_cot  --num_fewshot 4   --batch_size auto   --device cuda   --output_path ./eval_results/Qwen2.5_7B.jsonl   --log_samples   --seed 42 
lm-eval   --model hf   --model_args pretrained=/home/zhuhuixing/Projects/code/modelzoo/Qwen2.5-Math-7B-Instruct,dtype=auto,max_length=4096   --tasks gpqa_diamond_5_shot  --num_fewshot 5   --batch_size auto   --device cuda   --output_path ./eval_results/Qwen2.5_7B.jsonl   --log_samples   --seed 42 
lm-eval   --model hf   --model_args pretrained=/home/zhuhuixing/Projects/code/modelzoo/Qwen2.5-Math-7B-Instruct,dtype=auto,max_length=4096,parallelize=true   --tasks humaneval  --num_fewshot 0   --batch_size auto   --device cuda   --output_path ./eval_results/Qwen2.5_7B.jsonl   --log_samples   --seed 42 --confirm_run_unsafe_code
lm-eval   --model hf   --model_args pretrained=/home/zhuhuixing/Projects/code/modelzoo/Qwen2.5-Math-7B-Instruct,dtype=auto,max_length=4096,parallelize=true   --tasks mbpp_plus  --num_fewshot 0   --batch_size auto   --device cuda   --output_path ./eval_results/Qwen2.5_7B.jsonl   --log_samples   --seed 42 --confirm_run_unsafe_code